<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>3.0.0</Version>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnableHarmony>true</EnableHarmony>
		<EnableModZip>true</EnableModZip>
		<EnableModDeploy>false</EnableModDeploy>
		<GameModsPath>E:\SteamLibrary\steamapps\common\Stardew Valley\Mods</GameModsPath>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="releases\**" />
		<EmbeddedResource Remove="releases\**" />
		<None Remove="releases\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Examples\[SF] Example Pack\manifest.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Shaders\mask.mgfx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Shaders\opacity.mgfx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Shaders\wavy.mgfx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Textures\night_sky_sheet.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Textures\puddles_sheet.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Framework\Assets\Textures\sky_effects_sheet.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\de.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\default.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\fr.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ja.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ko.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\ru.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\th.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="i18n\zh.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
